# Generated by Django 4.1.2 on 2022-10-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_announcements_submissions_alter_report_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborlyHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytul')),
                ('name', models.CharField(max_length=200, verbose_name='Autor')),
                ('description', models.CharField(max_length=1000, verbose_name='Opis')),
                ('comment', models.JSONField(verbose_name='Komentarze')),
            ],
        ),
    ]
