# Generated by Django 4.1.2 on 2022-10-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_neighborlyhelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborlyhelp',
            name='comment',
            field=models.JSONField(null=True, verbose_name='Komentarze'),
        ),
    ]
