# Generated by Django 4.1.2 on 2022-10-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_neighborlyhelp_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborlyhelp',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='t_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.neighborlyhelp'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=400, verbose_name='Komentarz'),
        ),
    ]
