# Generated by Django 4.1.2 on 2022-10-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_neighborlyhelp_comment_comments_t_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='t_title',
            new_name='title',
        ),
    ]
